---
title       : Presentation of GDP Shiny App
subtitle    : Brief documentation for the GDP Shiny app
author      : Avi Blinder
framework   : io2012   # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
github:
    user: AviBlinder
    repo: GDP-Shiny-Presentation

---

## Introduction

>    1. The "GDP Shiny application" can be used to compare historical GDP 
>    rates between different countries.
>    
>    
>    2. The data for this application was downloaded from the [UNdata site]
>    (http://data.un.org/Default.aspx)
>
>
>    3. The dataset contains historical data from 1970 thru 2013 of 220 countries.
>

---

##  User Interface

    The application has two widgets:
    
    - A slider for choosing the range of years to be displayed.
    
    - A list of countries available on the dataset.
    
    - The output is a dynamic plot of GDP rates for multiple countries.

---

## Special features

>    1. The application builds the list of countries in an dynamic way, 
>    thru **renderUI** and **uiOutput** shiny funtions.

>    2. The application uses ggplot2 package and shows the comparison of
>    multiple countries, each having a different colour.
    

---

## Final words

    Please feel free to leave any feedback about this application.
    
    Hope you enjoy using it!!
    
    Thank you

This document was created at: 

```{r,echo=FALSE}
    Sys.Date()    
```
